name:                pagan
version:             0.1.0.0
github:              "mizlan/pagan"
license:             BSD3
author:              "Michael Lan"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pagan#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- time
- filepath
- process
- text
- monad-loops

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_pagan

executables:
  pagan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pagan
    when:
    - condition: false
      other-modules: Paths_pagan

tests:
  pagan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pagan
    when:
    - condition: false
      other-modules: Paths_pagan
